config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments, only: [:create,:destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update,:destroy] do
    resources :likes, only: [:index]
  end
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  is_impressionable counter_cache: true
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :comments
  
  mount_uploader :image, ImageUploader

  validates :title , presence: true
  validates :text , presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :validatable, password_length: 8..128

  has_many :posts ,dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments

  mount_uploader :icon, IconImageUploader

  validates :nickname , presence: true, length: { maximum: 8 }
  validates :email, presence: true, 
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "は@とドメインを含んだものを入力してください" }, 
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, format: { with: /\A[a-zA-Z0-9]+\z/, message: "は半角英数字で入力してください"}, length: { minimum: 8 }, on: :create
  validates :bgi , presence: true
  validates :introduction , length: { maximum: 350 }
  
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:icon,:bgi])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.create(content: comment_params[:content], post_id: comment_params[:post_id], user_id: current_user.id)
    if @comment.save
      redirect_to post_path(@comment.post.id)
    else
      redirect_to post_path(@comment.post.id)
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post.id)
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :time, only:[:index, :show,:new,:edit]
  PER = 7
  def index
    @user = current_user
    @posts = @user.liked_posts.order("created_at DESC").page(params[:page]).per(PER)
  end

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def time
    @d = Date.today
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_params, only:[:show,:edit,:destroy]
  before_action :time, only:[:index, :show,:new,:edit]
  before_action :move_to_new, except: [:index,:show]
  before_action :move_to_edit, only: [:edit]
  PER = 7

  def index
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(PER)
    @ranking = Post.all.order('impressions_count DESC').limit(6)
                  # .where("? <= created_at", Time.now.week)
                  # .where("created_at <= ?", Time.now).take(6)
  end

  def show
    impressionist(@post, nil)
    @like = Like.new
    @comment = Comment.new
    @comments = @post.comments.includes(:post).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    if post.save
      redirect_to root_path and return
    else
      redirect_to new_post_path and return
    end
  end

  def edit
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    if post.save
      redirect_to root_path and return
    else
      redirect_to new_post_path and return
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private 

  def post_params
    params.require(:post).permit(:title,:text,:image).merge(user_id: current_user.id)
  end

  def set_params
    @post = Post.find(params[:id])
  end

  def time
    @d = Date.today
  end

  def move_to_new
    redirect_to action: :index unless user_signed_in?
  end
  
  def move_to_edit
    @post = Post.find(params[:id])
    if @post.user_id != current_user.id
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :time, only:[:index, :show,:new,:edit]
  before_action :set_params, only:[:show,:edit,:destroy]
  before_action :move_to_edit, only:[:edit]
  PER = 7

  def new
    
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to root_path and return
    else
      redirect_to new_user_registration_path and return
    end
  end

  def show
    @post = @user.posts
    @posts = @post.order("created_at DESC").page(params[:page]).per(PER)
  end

  def edit

  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path and return
    else
      redirect_to edit_user_path and return
    end
  end

  def destroy
    if @user.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private
  def user_params
    params.require(:user).permit(:nickname,:icon,:bgi,:email,:encrypted_password,:introduction)
  end

  def set_params
    @user = User.find(params[:id])
  end

  def time
    @d = Date.today
  end

  def move_to_edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_blog_comment.html.haml
.comment_zone
  - if @comments
    - @comments.each do |c|
      .comment_zone-box
        - if user_signed_in?
          - if current_user.id == c.post.user.id or c.user.id == current_user.id
            .comment_zone-box-leftactive
              .comment_time
                .comment_time-area
                  = c.created_at.strftime("%Y.%m.%d %H:%M")
              .comment
                = simple_format(c.content)
              .comment_user
                .comment_username
                  = c.user.nickname
              = link_to 'コメント削除',post_comment_path(@post,c) , method: :delete,class:'comment_userdelete',data: { confirm: '本当によろしいですか?' }
            .comment_zone-box-rightactive
              - if c.user.icon.present?
                = link_to image_tag(c.user.icon.url,size:"80x80",class:"comment_usericon"),user_path(c.user.id)
              - else
                = link_to image_tag(asset_path('new_baby.png'),size:"80x80",class:"comment_usericon"),user_path(c.user.id)
          - else
            .comment_zone-box-left
              - if c.user.icon.present?
                = link_to image_tag(c.user.icon.url,size:"80x80",class:"comment_usericon"),user_path(c.user.id)
              - else
                = link_to image_tag(asset_path('new_baby.png'),size:"80x80",class:"comment_usericon"),user_path(c.user.id)
            .comment_zone-box-right
              .comment_time
                .comment_time-area
                  = c.created_at.strftime("%Y.%m.%d %H:%M")
              .comment
                = simple_format(c.content)
              .comment_user
                .comment_username
                  = c.user.nickname
        - else
          .comment_zone-box-left
            - if c.user.icon.present?
              = link_to image_tag(c.user.icon.url,size:"80x80",class:"comment_usericon"),user_path(c.user.id)
            - else
              = link_to image_tag(asset_path('new_baby.png'),size:"80x80",class:"comment_usericon"),user_path(c.user.id)
          .comment_zone-box-right
            .comment_time
              .comment_time-area
                = c.created_at.strftime("%Y.%m.%d %H:%M")
            .comment
              = simple_format(c.content)
            .comment_user
              .comment_username
                = c.user.nickname
- if user_signed_in?
  .comment_area
    = form_with(model: [@post,@comment], local: true,class:"comment_area-form") do |f|
      = f.text_area :content, placeholder: "コメント", class: "comment_box"
      = f.submit class:"comment_submit"
  .comment_submit-area
    .submit_dammy 送信

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BabyBlogs
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/likes/_likebtn.html.haml
- if user_signed_in?
  - if current_user.already_liked?(@post)
    = button_to 'いいね',post_like_path(@post), method: :delete,class:'likebtn'
    .likebtn_dammy.like_on
      %i.far.fa-thumbs-up
      .likebtn_dammycount.like_on-count
        いいね #{@post.likes.count}
  - else
    = button_to 'いいね',post_likes_path(@post),class:'likebtn'
    .likebtn_dammy
      %i.far.fa-thumbs-up
      .likebtn_dammycount
        いいね #{@post.likes.count}
- else 
  .likebtn いいね
  .likebtn_dammy
    %i.far.fa-thumbs-up
    .likebtn_dammycount
      いいね #{@post.likes.count}

app/views/likes/index.html.haml
= render 'posts/header'
%h1.showpost_title
  = link_to 'Baby BLOGs', root_path,class:'newpost_titlelogo'
= render 'users/usershow'
.show_info
  .show_info-left
    .show_info-leftname
      = @user.nickname
.like_area
  .like_area-box
    .like_area-boxinfo User Like List
    %i.far.fa-thumbs-up
= render 'posts/blog'
= render 'posts/footer'

app/views/posts/_blog.html.haml
.main_content
  .main_content-box
    .article-list
      - @posts.each do |p|
        .article.b-article.fadein
          - if p.image.present?
            %figre.article-image
              = link_to (image_tag p.image.url,class:'image'),post_path(p.id)
          - else
            %figre.article-image
              = link_to image_tag(asset_path('noimage.jpeg'), class:'image cover'),post_path(p.id)
              .image_box NonImage
          .article_text-box
            .article_text-box-top
              %p.article_logo BLOG
              %a{href:post_path(p.id),class:'article_title'}
                .article_title-b
                  = p.title
                %p.article_time
                  = p.created_at.strftime("%Y.%m.%d %H:%M")
                %p.article_summary
                  = simple_format(p.text.truncate(150,omission: '...'))
            .article_text-box-bottom
      = paginate @posts

app/views/posts/_footer.html.haml
%footer.main_footer
  .main_footer-left
    = link_to 'Baby BLOGs', root_path,class:'footer_title'
    .footer_sns
      EXPAND → 
      = link_to '#' do
        %i.fab.fa-twitter
      = link_to '#' do
        %i.fab.fa-facebook-square
  .main_footer-center
    %ul.menu
      %li.menu_list
        = link_to 'HOME', '#',class:'menu_list-btn'
      %li.menu_list
        = link_to 'Baby BLOGsとは?', '#',class:'menu_list-btn'
      %li.menu_list
        = link_to 'よくある質問', '#',class:'menu_list-btn'
      %li.menu_list
        = link_to 'お知らせ', '#',class:'menu_list-btn'
      %li.menu_list
        = link_to 'お問い合わせ', '#',class:'menu_list-btn'
  .main_footer-right
    %ul.menu
      %li.menu_list
        = link_to 'ランキング', '#',class:'menu_list-btn'
      %li.menu_list
        = link_to 'プライバシーポリシー', '#',class:'menu_list-btn'
      %li.menu_list
        = link_to 'SNS連携', '#',class:'menu_list-btn'
      %li.menu_list
        = link_to 'メルマガ', '#',class:'menu_list-btn'
      %li.menu_list
        = link_to 'その他', '#',class:'menu_list-btn'
.main_footer-bottom
  = "Copyright (C) #{@d.strftime("%Y")} Baby BLOGs All Rights Reserved."

app/views/posts/_header.html.haml
%header.main_header
  %h1.main_header-title
    = link_to 'Baby BLOGs', root_path,class:'main_header-titlelogo'
  .main_header-link
    %nav.bnav
      %ul.bnav-options
        %li.bnav_items
          = link_to 'NEW',new_post_path,class:'item'
        %li.bnav_items
          = link_to 'MYBLOG','#',class:'item'
        %li.bnav_items
          = link_to 'INFO','#',class:'item'
        %li.bnav_items
          - if user_signed_in?
            = link_to 'LOGOUT',destroy_user_session_path,method: :delete,class:'item'
            .icon_area
              - if current_user.icon.present?
                = link_to image_tag(current_user.icon.url,size:'40x40',class:'user_icon'),user_path(current_user.id)
              - else
                = link_to image_tag(asset_path('new_baby.png'),size:'40x40',class:'user_icon'),user_path(current_user.id)
          - else
            = link_to 'LOGIN',new_user_session_path,class:'item'
    .bsearch
      %form.search
        %input{type:'text' ,placeholder:'Search',class:'bsearch_input',size:'15px',style:'font-size: 1rem'}
        %button{type:'submit', class:'bsearch_btn'} Search
        %i.fas.fa-search
  .b-header
  %nav.snav
    %ul.snav-options
      %li.snav_icon
        = link_to '#' do
          %i.fab.fa-twitter
      %li.snav_icon
        = link_to '#' do
          %i.fab.fa-facebook-square

app/views/posts/_loading.html.haml
.loading
  .loading_box
    %span.loading_box-logo
      %span B
      %span a
      %span b
      %span y
      %span B
      %span L
      %span O
      %span G
      %span s

app/views/posts/_ranking.html.haml
.ranking_content.fadein
  .ranking_content-box
    .ranking_name ACCESS RANKING
    - @ranking.each_with_index do |r, i|
      .ranking
        .ranking_box.ranking_box-back.ranking_box-zoom
          .ranking_image-fakebox
            .ranking_number
              = i + 1
          - if r.image.present?
            = link_to (image_tag r.image.url,class:'ranking_image',size: '300x185'),post_path(r.id)
          - else
            = link_to image_tag(asset_path('noimage.jpeg'),class:'ranking_image',size: '300x185'),post_path(r.id)
          .ranking_title
            = r.title.truncate(17,omission: '...')
          .ranking_count
            = "#{r.impressions_count} view"

app/views/posts/_show_blog.html.haml
.show_main
  .show_main-article
  - if @post.image.present?
    .show_main-article-image
      = image_tag @post.image.url, class:'show_image'
      .img_article
        .img_article-title
          = @post.title
        .img_article-created
          = @post.created_at.strftime("%Y.%m.%d %H:%M")
        .img_article-view
          = "#{@post.impressions_count} view"
      - if user_signed_in? && current_user.id == @post.user_id
        = link_to '編集', edit_post_path(@post.id),method: :get,class:'edit_btn'
        = link_to '削除',post_path(@post.id),method: :delete, class:'delete_btn'
      - else
        = render 'likes/likebtn'
    .show_main-article-content
      %nav.article_sns
        %ul.article_sns-box
          = link_to '#' do
            %li.sns_icon-twitter
              %i.fab.fa-twitter
              ツイート
          = link_to '#' do
            %li.sns_icon-facebook
              %i.fab.fa-facebook-square
              シェア
      .article_border
      .article
        .article_text
          = simple_format(@post.text)
        .article_user
          = link_to @post.user.nickname, '#'
      .article_border
  - else
    .show_main-article-image
      = image_tag asset_path('noimage.jpeg'),size:'850x525', class:'show_image'
      .img_article
        .img_article-title
          = @post.title
        .img_article-created
          = @post.created_at.strftime("%Y.%m.%d %H:%M")
        .img_article-view
          = "#{@post.impressions_count} view"
      - if user_signed_in? && current_user.id == @post.user_id
        = link_to '編集', edit_post_path(@post.id),method: :get,class:'edit_btn'
        = link_to '削除',post_path(@post.id), method: :delete, class:'delete_btn'
      - else
        = render 'likes/likebtn'
    .show_main-article-content
      %nav.article_sns
        %ul.article_sns-box
          = link_to '#' do
            %li.sns_icon-twitter
              %i.fab.fa-twitter
              ツイート
          = link_to '#' do
            %li.sns_icon-facebook
              %i.fab.fa-facebook-square
              シェア
      .article_border
      .article
        .article_text
          = simple_format(@post.text)
        .article_user
          = link_to @post.user.nickname, '#'
      .article_border

app/views/posts/edit.html.haml
= render 'posts/header'
%h1.editpost_title
  = link_to 'Baby BLOGs', root_path,class:'editpost_titlelogo'
.dammy_block
.post
  .post_form
    = form_with(model: @post, local: true) do |f|
      = f.text_field :title, class:'post_title',placeholder:'Blog Title'
      .image_field 
        - if @post.image.present?
          = image_tag @post.image.url,class:'image_area'
        - else
          = image_tag asset_path('noimage.jpeg'),size:'850x525',class:'image_area'
        = f.file_field :image, class:'image_form'
        .image_form-btn Image Select
      .text_box.bootstrap
        = f.text_area :text, class:'post_text','data-provider': :summernote
      = f.submit '投稿', class:'post_submit'
      .post_submit-dammy 投稿
= render 'posts/footer'

app/views/posts/index.html.haml
= render 'posts/loading'
.containe
  %header.top
    .top_logo
      .top_logo-name Baby BLOGs
    %figure.top_logoarea
      = image_tag asset_path('top.jpeg'), class: "top_logoarea-image"
  .fake
  .main
    = render 'posts/header'
    = render 'posts/blog'
    = render 'posts/ranking'
    = render 'posts/footer'
  .top_scroll
    .top_scroll-btn
      %i.fas.fa-angle-up

app/views/posts/new.html.haml
= render 'posts/header'
%h1.newpost_title
  = link_to 'Baby BLOGs', root_path,class:'newpost_titlelogo'

.dammy_block
.post
  .post_form
    = form_with(model: @post, local: true) do |f|
      = f.text_field :title, class:'post_title',placeholder:'Blog Title'
      .image_field 
        %p.image_field-info
          Image Select
        = image_tag asset_path('baby_image.jpeg'),class:'image_area'
        = f.file_field :image, class:'image_form'
        .image_form-btn Image Select
      .text_box.bootstrap
        = f.text_area :text, class:'post_text','data-provider': :summernote
      = f.submit '投稿', class:'post_submit'
      .post_submit-dammy 投稿
= render 'posts/footer'

app/views/posts/show.html.haml
= render 'posts/header'
%h1.newpost_title
  = link_to 'Baby BLOGs', root_path,class:'newpost_titlelogo'
= render 'posts/show_blog'
= render 'comments/blog_comment'
= render 'posts/footer'

app/views/users/_blog.html.haml
.main_content
  .main_content-box
    .article-list
      - @posts.each do |i|
        .article.b-article.fadein
          - if i.image.present?
            %figre.article-image
              = link_to (image_tag i.image.url,class:'image'),post_path(i.id)
          - else
            %figre.article-image
              = link_to image_tag(asset_path('noimage.jpeg'), class:'image cover'),post_path(i.id)
              .image_box NonImage
          .article_text-box
            .article_text-box-top
              %p.article_logo BLOG
              %a{href:post_path(i.id),class:'article_title'}
                .article_title-b
                  = i.title
                %p.article_time
                  = i.created_at.strftime("%Y.%m.%d %H:%M")
                %p.article_summary
                  = simple_format(i.text.truncate(150,omission: '...'))
            .article_text-box-bottom
      = paginate @posts

app/views/users/_usershow.html.haml
.user_show
  - if @user.bgi == "背景1"
    = image_tag asset_path('show_header1.jpeg'),class:'user_show-header',size:'1050x250'
  - elsif @user.bgi == "背景2"
    = image_tag asset_path('show_header2.jpeg'),class:'user_show-header',size:'1050x250'
  - elsif @user.bgi == "背景3"
    = image_tag asset_path('show_header3.jpeg'),class:'user_show-header',size:'1050x250'
  - elsif @user.bgi == "背景4"
    = image_tag asset_path('show_header4.jpeg'),class:'user_show-header',size:'1050x250'
  - elsif @user.bgi == "背景5"
    = image_tag asset_path('show_header5.jpeg'),class:'user_show-header',size:'1050x250'
  - elsif @user.bgi == "背景6"
    = image_tag asset_path('show_header6.jpeg'),class:'user_show-header',size:'1050x250'
  - elsif @user.bgi == "背景7"
    = image_tag asset_path('show_header7.jpeg'),class:'user_show-header',size:'1050x250'
  .user_show-box
    .user_show-boxarea
      .user_iconarea
        - if @user.icon.present?
          = image_tag @user.icon.url ,class:'usershow_icon',size:'120x120'
        - else
          = image_tag asset_path('new_baby.png'),class:'usershow_icon',size:'120x120'
      .user_follow
        .user_follow-box
          .follow_btn フォローする
      .user_setting
        %i.fas.fa-bars
    .edit_box.clear_box
      = link_to 'いいねリスト',user_likes_path(@user.id),class:'user_edit'
      = link_to 'ユーザー編集',edit_user_path(@user.id),class:'user_edit'
      = link_to 'ユーザー削除',user_path(@user.id),method: :delete,data: {confirm: "削除しますか？"},class:'user_edit'
      = link_to 'ログアウト',destroy_user_session_path,method: :delete,class:'user_edit'
      .close_btn 閉じる

app/views/users/edit.html.haml
= render 'posts/header'
%h1.showpost_title
  = link_to 'Baby BLOGs', root_path,class:'newpost_titlelogo'
.user_editcontent
  = form_with(model: @user, local: true) do |f|
    .dammy_block
    .user_show
      - if @user.bgi == "背景1"
        = image_tag asset_path('show_header1.jpeg'),class:'user_show-header',size:'1050x250'
      - elsif @user.bgi == "背景2"
        = image_tag asset_path('show_header2.jpeg'),class:'user_show-header',size:'1050x250'
      - elsif @user.bgi == "背景3"
        = image_tag asset_path('show_header3.jpeg'),class:'user_show-header',size:'1050x250'
      - elsif @user.bgi == "背景4"
        = image_tag asset_path('show_header4.jpeg'),class:'user_show-header',size:'1050x250'
      - elsif @user.bgi == "背景5"
        = image_tag asset_path('show_header5.jpeg'),class:'user_show-header',size:'1050x250'
      - elsif @user.bgi == "背景6"
        = image_tag asset_path('show_header6.jpeg'),class:'user_show-header',size:'1050x250'
      - elsif @user.bgi == "背景7"
        = image_tag asset_path('show_header7.jpeg'),class:'user_show-header',size:'1050x250'
      .image_select-area
      .user_show-box
        .user_show-boxarea
          .user_iconarea
            - if @user.icon.present?
              = image_tag @user.icon.url ,class:'usershow_icon',size:'120x120'
            - else
              = image_tag asset_path('new_baby.png'),class:'usershow_icon',size:'120x120'
          = f.file_field :icon, class:'icon_change-dammy'
          .icon_change-info プロフィール画像変更
          .icon_change 画像選択
      .change_field
        .change_name-area
          .name_change-info ニックネーム変更
          = f.text_field :nickname , class:'user_namechange',placeholder:'ニックネームを入力してください'
          .bgi_change-info 背景画像変更
          = f.select :bgi,[['Flowers other','背景1'],['Tree','背景2'],['Starry sky','背景3'],['Mountain','背景4'],['Butterfly','背景5'],['Plant','背景6'],['Other','背景7'],],class:'bgi_change',name:'bgi'
        .change_introduction-area
          = f.text_area :introduction , class:'introduction_change',placeholder:'自己紹介など(350文字まで)'
          .count 0/350 文字
      .submit_area
        = f.submit '変更', class:'change_btn'
        .change_btn-fake 変更
= render 'posts/footer'

app/views/users/show.html.haml
= render 'posts/header'
%h1.showpost_title
  = link_to 'Baby BLOGs', root_path,class:'newpost_titlelogo'
.dammy_block
= render 'users/usershow'
.show_info
  .show_info-left
    .show_info-leftname
      = @user.nickname
    .show_info-leftfollow
      100 フォロー中  200 フォロワー 
    .show_info-leftarticle
      = "記事数 : #{@post.length}"
  .show_info-right
    .show_info-rightintroduction
      Introduction
      .show_info-rightintroduction-area
        = simple_format(@user.introduction)
.show_article
  = render 'users/blog'
= render 'posts/footer'